### ISSUE TITLE
Allow for using in subfolder with SWAG

### ISSUE THREAD

**Issue by martimarkov** [linuxserver/docker-baseimage-rdesktop-web#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Allow for using derivative containers to be behind a proxy within a subfolder. 
------------------------------

I think the change that needs to happen in https://github.com/linuxserver/gclient but I'm not sure.

**Comment by martimarkov** [comment]
Example:

```
location ^~ /sqlitebrowser/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app sqlitebrowser;
    set $upstream_port 3000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port/;
}```

This should work but unfortunately every single static resource returns a 404 from the TLD

So when accessing `https://example.com/sqlitebrowser/` the static resources are loaded from `https://example.com/public/` instead of `https://example.com/sqlitebrowser/public/`

**Comment by thelamer** [comment]
this was added as `-e SUBFOLDER=/` env var for the container.
